<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>regression_analysis</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="dashboard.html">Dashboard</a>
</li>
<li>
  <a href="mailto:&lt;zh2494@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/zh2494/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/zhuolun-huang-60246620a/">
    <span class="fa fa-linkedin fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<div id="regression-analysis" class="section level1">
<h1>Regression Analysis</h1>
<p>Lin Yang 11/20/2021</p>
<div id="create-a-data-frame-for-regression-analysis" class="section level2">
<h2>Create a data frame for regression analysis</h2>
<p>Load and clean air quality datasets for 100 cities.</p>
<pre class="r"><code>city_100_df = tibble(
  file = list.files(&quot;100_cities_data&quot;)) %&gt;% 
  mutate(
    city = str_remove(file, &quot;-air-quality.csv&quot;),
    path = str_c(&quot;100_cities_data/&quot;, file),
    data = map(path, read_csv)
  ) %&gt;% 
  unnest(data) %&gt;% 
  select(-file, -path) %&gt;% 
  mutate(
    city = str_to_title(city),
    date = as.Date(date, format = &quot;%Y/%m/%d&quot;))</code></pre>
<p>Select pm2.5 AQI during the lockdown period (Feb-Apr) for both 2019 and 2020.</p>
<pre class="r"><code>pm25_2020 = 
  city_100_df %&gt;% 
  filter(date &gt; &quot;2020-01-31&quot; &amp; date &lt; &quot;2020-05-01&quot;) %&gt;% 
  rename(pm25_2020 = pm25) %&gt;% 
  mutate(date = format(date, format = &quot;%m-%d&quot;)) %&gt;% 
  select(city, date, pm25_2020)
  
pm25_2019 = 
  city_100_df %&gt;% 
  filter(date &gt; &quot;2019-01-31&quot; &amp; date &lt; &quot;2019-05-01&quot;) %&gt;% 
  rename(pm25_2019 = pm25) %&gt;% 
  mutate(date = format(date, format = &quot;%m-%d&quot;)) %&gt;% 
  select(city, date, pm25_2019)</code></pre>
<p>Calculate daily pm2.5 AQI differences between 2019 and 2020 for each city.</p>
<pre class="r"><code>pm25_diff = 
  left_join(pm25_2020, pm25_2019, by = c(&quot;city&quot;, &quot;date&quot;)) %&gt;% 
  drop_na() %&gt;% 
  mutate(pm25_diff = pm25_2019 - pm25_2020) %&gt;% 
  group_by(city) %&gt;% 
  summarize(mean_diff = mean(pm25_diff, na.rm = T))

pm25_diff</code></pre>
<pre><code>## # A tibble: 100 × 2
##    city      mean_diff
##    &lt;chr&gt;         &lt;dbl&gt;
##  1 Anyang        45.5 
##  2 Baoding       28.4 
##  3 Baotou         6.53
##  4 Beijing       16.0 
##  5 Cangzhou      23.3 
##  6 Changchun      1.18
##  7 Changde        1.61
##  8 Changsha       4.03
##  9 Changzhou     27.1 
## 10 Chengdu       10.5 
## # … with 90 more rows</code></pre>
<p>Load the gdp and population dataset and join it to <code>pm25_diff</code>.</p>
<pre class="r"><code>gdp_pop_df = 
  read_csv(&quot;data/gpd_and_popluation.csv&quot;) %&gt;% 
  janitor::clean_names() %&gt;% 
  mutate(pop_ln = log(population_thousand, base = exp(1)),
         gdp_ln = log(gdp_billion, base = exp(1))) %&gt;% 
  select(city, gdp_ln, pop_ln)

diff_gdp_pop_df = left_join(pm25_diff, gdp_pop_df) 
diff_gdp_pop_df</code></pre>
<pre><code>## # A tibble: 100 × 4
##    city      mean_diff gdp_ln pop_ln
##    &lt;chr&gt;         &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 Anyang        45.5    5.65   8.55
##  2 Baoding       28.4    5.96   9.37
##  3 Baotou         6.53   5.69   7.97
##  4 Beijing       16.0    8.17   9.99
##  5 Cangzhou      23.3    5.88   8.93
##  6 Changchun      1.18   6.38   8.99
##  7 Changde        1.61   5.89   8.67
##  8 Changsha       4.03   7.14   9.01
##  9 Changzhou     27.1    6.61   8.56
## 10 Chengdu       10.5    7.44   9.70
## # … with 90 more rows</code></pre>
<p>We learned that air quality improvement in a city may correlates to the city’s GDP and population, so we created a data frame containing mean pm2.5 AQI differences between 2019 and 2020, GDP and population in 2019 for 100 representative cities. The resulting data frame of <code>diff_gdp_pop_df</code> contains 100 observations of 4 variables. Each row represents one unique city. Below are key variables: <code>city</code>: city name <code>mean_diff</code> mean pm2.5 AQI difference during the lockdown period (Feb-Apr) between 2019 and 2020. <code>gdp_ln</code>: log of 2019 GDP in billions <code>pop_ln</code>: log of 2019 population in thousands</p>
</div>
<div id="fit-linear-models" class="section level2">
<h2>Fit linear models</h2>
<pre class="r"><code>fit = lm(mean_diff ~gdp_ln + pop_ln, data = diff_gdp_pop_df)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mean_diff ~ gdp_ln + pop_ln, data = diff_gdp_pop_df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -22.9298  -9.3085  -0.2823   9.0568  30.3316 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  -4.6251    19.5716  -0.236    0.814
## gdp_ln       -0.8938     2.3591  -0.379    0.706
## pop_ln        2.9034     3.0895   0.940    0.350
## 
## Residual standard error: 11.16 on 94 degrees of freedom
##   (3 observations deleted due to missingness)
## Multiple R-squared:  0.0111, Adjusted R-squared:  -0.009941 
## F-statistic: 0.5275 on 2 and 94 DF,  p-value: 0.5918</code></pre>
<pre class="r"><code>fit %&gt;% 
  broom::tidy() %&gt;% 
  select(term, estimate, p.value) %&gt;% 
  knitr::kable(digit = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-4.625</td>
<td align="right">0.814</td>
</tr>
<tr class="even">
<td align="left">gdp_ln</td>
<td align="right">-0.894</td>
<td align="right">0.706</td>
</tr>
<tr class="odd">
<td align="left">pop_ln</td>
<td align="right">2.903</td>
<td align="right">0.350</td>
</tr>
</tbody>
</table>
<p>After fitting a linear model for mean pm2.5 AQI difference dependent on gdp_ln and pop_ln, gdp_ln variable has a slope of -0.894 and pop_ln variable has a slope of 2.903. However, p values of the two linear models are both very large. Therefore, we don’t have enough evidence to support that air quality improvement has a linear relation with GDP and population.</p>
</div>
<div id="model-diagnostics" class="section level2">
<h2>Model Diagnostics</h2>
<pre class="r"><code>diff_gdp_pop_df %&gt;% 
  modelr::add_residuals(fit) %&gt;% 
  ggplot(aes(x = gdp_ln, y = resid)) + geom_violin()</code></pre>
<p><img src="regression_analysis_files/figure-gfm/unnamed-chunk-7-1.png" width="90%" /></p>
<pre class="r"><code>diff_gdp_pop_df %&gt;% 
  modelr::add_residuals(fit) %&gt;% 
  ggplot(aes(x = pop_ln, y = resid)) + geom_violin()</code></pre>
<p><img src="regression_analysis_files/figure-gfm/unnamed-chunk-7-2.png" width="90%" /></p>
</div>
<div id="cross-validation" class="section level2">
<h2>Cross Validation</h2>
<p>Fit three models for <code>mean_diff</code> vs. <code>gdp_ln</code>.</p>
<pre class="r"><code>linear_mod_gdp = lm(mean_diff ~ gdp_ln, data = diff_gdp_pop_df)
smooth_mod_gdp = gam(mean_diff ~ s(gdp_ln), data = diff_gdp_pop_df)
wiggly_mod_gdp = gam(mean_diff ~ s(gdp_ln, k = 30), sp = 10e-6, data = diff_gdp_pop_df)
diff_gdp_pop_df %&gt;% 
  gather_predictions(linear_mod_gdp, smooth_mod_gdp, wiggly_mod_gdp) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = gdp_ln, y = mean_diff)) + 
  geom_point(alpha = .5) +
  geom_line(aes(y = pred), color = &quot;red&quot;) + 
  facet_grid(~model) +
  labs(
    x = &quot;log(GDP in Billion)&quot;,
    y = &quot;Mean Daily PM2.5 AQI Difference&quot;)</code></pre>
<p><img src="regression_analysis_files/figure-gfm/unnamed-chunk-8-1.png" width="90%" /></p>
<p>Fit three models for <code>mean_diff</code> vs. <code>pop_ln</code>.</p>
<pre class="r"><code>linear_mod_pop = lm(mean_diff ~ pop_ln, data = diff_gdp_pop_df)
smooth_mod_pop = gam(mean_diff ~ s(pop_ln), data = diff_gdp_pop_df)
wiggly_mod_pop = gam(mean_diff ~ s(pop_ln, k = 30), sp = 10e-6, data = diff_gdp_pop_df)
diff_gdp_pop_df %&gt;% 
  gather_predictions(linear_mod_pop, smooth_mod_pop, wiggly_mod_pop) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = pop_ln, y = mean_diff)) + 
  geom_point(alpha = .5) +
  geom_line(aes(y = pred), color = &quot;red&quot;) + 
  facet_grid(~model) +
  labs(
    x = &quot;log(Population in Thousand)&quot;,
    y = &quot;Mean Daily PM2.5 AQI Difference&quot;)</code></pre>
<p><img src="regression_analysis_files/figure-gfm/unnamed-chunk-9-1.png" width="90%" /></p>
<p>Cross validation for <code>mean_diff</code> vs. <code>gdp_ln</code>.</p>
<pre class="r"><code>cv_df_gdp = 
  crossv_mc(diff_gdp_pop_df, 100) %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) %&gt;% 
  mutate(
    linear_mod  = map(train, ~lm(mean_diff ~ gdp_ln, data = .x)),
    smooth_mod  = map(train, ~mgcv::gam(mean_diff ~ s(gdp_ln), data = .x)),
    wiggly_mod  = map(train, ~gam(mean_diff ~ s(gdp_ln, k = 30), sp = 10e-6, data = .x))) %&gt;% 
  mutate(
    rmse_linear = map2_dbl(linear_mod, test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(smooth_mod, test, ~rmse(model = .x, data = .y)),
    rmse_wiggly = map2_dbl(wiggly_mod, test, ~rmse(model = .x, data = .y))) %&gt;% 
  select(starts_with(&quot;rmse&quot;)) %&gt;%
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;) 

cv_df_gdp %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin(aes(fill = model), alpha = 0.5) +
  labs(title = &quot;RMSE vs. Model&quot;)</code></pre>
<p><img src="regression_analysis_files/figure-gfm/unnamed-chunk-10-1.png" width="90%" /></p>
<p>Cross validation for <code>mean_diff</code> vs. <code>pop_ln</code>.</p>
<pre class="r"><code>cv_df_pop = 
  crossv_mc(diff_gdp_pop_df, 100) %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) %&gt;% 
  mutate(
    linear_mod  = map(train, ~lm(mean_diff ~ pop_ln, data = .x)),
    smooth_mod  = map(train, ~mgcv::gam(mean_diff ~ s(pop_ln), data = .x)),
    wiggly_mod  = map(train, ~gam(mean_diff ~ s(pop_ln, k = 30), sp = 10e-6, data = .x))) %&gt;% 
  mutate(
    rmse_linear = map2_dbl(linear_mod, test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(smooth_mod, test, ~rmse(model = .x, data = .y)),
    rmse_wiggly = map2_dbl(wiggly_mod, test, ~rmse(model = .x, data = .y))) %&gt;% 
  select(starts_with(&quot;rmse&quot;)) %&gt;%
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;)

cv_df_pop %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin(aes(fill = model), alpha = 0.5) +
  labs(title = &quot;RMSE vs. Model&quot;)</code></pre>
<p><img src="regression_analysis_files/figure-gfm/unnamed-chunk-11-1.png" width="90%" /> We then did cross validation for three different kinds of models of mean PM2.5 difference vs. gdp_ln and pop_ln. The scatterplots indicated that none of the three models were good fits. For both gdp_ln and pop_ln, the distribution of RMSE values for each model suggested that linear and smooth models worked better than wiggly model. But the RMSE values of all the three models were significantly large, confirming all of them were bad fits.</p>
</div>
<div id="create-a-data-frame-containing-weather-data-for-regression-analysis" class="section level2">
<h2>Create a data frame containing weather data for regression analysis</h2>
<p>Load weather data for 10 representative cities.</p>
<pre class="r"><code>weather_df = 
  rnoaa::meteo_pull_monitors(
    c(&quot;CHM00054511&quot;, &quot;CHM00058362&quot;, &quot;CHM00050953&quot;, &quot;CHM00054342&quot;, &quot;CHM00055591&quot;, &quot;CHM00056294&quot;, &quot;CHM00056778&quot;, &quot;CHM00059287&quot;, &quot;CHM00057036&quot;, &quot;CHM00057494&quot;),
    var = c(&quot;PRCP&quot;, &quot;TAVG&quot;), 
    date_min = &quot;2020-02-01&quot;,
    date_max = &quot;2020-04-30&quot;) %&gt;%
  mutate(
    name = recode(
      id, 
      CHM00054511 = &quot;Beijing&quot;, 
      CHM00058362 = &quot;Shanghai&quot;,
      CHM00050953 = &quot;Harbin&quot;,
      CHM00054342 = &quot;Shenyang&quot;,
      CHM00055591 = &quot;Lasa&quot;,
      CHM00056294 = &quot;Chengdu&quot;,
      CHM00056778 = &quot;Kunming&quot;,
      CHM00059287 = &quot;Guangzhou&quot;,
      CHM00057036 = &quot;Xian&quot;,
      CHM00057494 = &quot;Wuhan&quot;),
    tavg = tavg / 10,
    prcp = prcp / 10) %&gt;%
  select(-id) %&gt;% 
  rename(city = name) %&gt;% 
  relocate(city)

weather_df</code></pre>
<pre><code>## # A tibble: 900 × 4
##    city    date        prcp  tavg
##    &lt;chr&gt;   &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt;
##  1 Beijing 2020-02-01   1     1.6
##  2 Beijing 2020-02-02   0.3  -2.8
##  3 Beijing 2020-02-03   0    -2.6
##  4 Beijing 2020-02-04   0    -4.1
##  5 Beijing 2020-02-05   2.8  -6  
##  6 Beijing 2020-02-06   1.3  -6.1
##  7 Beijing 2020-02-07   0    -4.4
##  8 Beijing 2020-02-08   0    -0.6
##  9 Beijing 2020-02-09   0    -0.5
## 10 Beijing 2020-02-10   0     1.8
## # … with 890 more rows</code></pre>
<p>Join <code>weather_df</code> to the AQI dataset of 10 cities.</p>
<pre class="r"><code>city_10_df =
  city_100_df %&gt;% 
  filter(date &gt; &quot;2020-01-31&quot; &amp; date &lt; &quot;2020-05-01&quot;) %&gt;% 
  filter(city %in% c(&quot;Beijing&quot;, &quot;Shanghai&quot;, &quot;Harbin&quot;, &quot;Shenyang&quot;, &quot;Lasa&quot;, &quot;Chengdu&quot;, &quot;Kunming&quot;, &quot;Guangzhou&quot;, &quot;Xian&quot;, &quot;Wuhan&quot;))

pm25_tavg_df = 
  left_join(city_10_df, weather_df, by = c(&quot;city&quot;, &quot;date&quot;)) %&gt;% 
  arrange(date) %&gt;% 
  select(city, date, pm25, tavg) %&gt;% 
  drop_na() 

pm25_tavg_df</code></pre>
<pre><code>## # A tibble: 794 × 4
##    city      date        pm25  tavg
##    &lt;chr&gt;     &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt;
##  1 Beijing   2020-02-01   120   1.6
##  2 Chengdu   2020-02-01   120   8.8
##  3 Guangzhou 2020-02-01    84  15.6
##  4 Harbin    2020-02-01   240 -14.9
##  5 Kunming   2020-02-01    75   9.3
##  6 Shanghai  2020-02-01   126   4.9
##  7 Shenyang  2020-02-01   257  -9.4
##  8 Wuhan     2020-02-01   168  10  
##  9 Xian      2020-02-01   197   5.3
## 10 Beijing   2020-02-02    30  -2.8
## # … with 784 more rows</code></pre>
<pre class="r"><code>pm25_tavg_df %&gt;% 
  ggplot(aes(x = tavg, y = pm25)) +
  geom_point() +
  labs(
    x = &quot;Daily Average Temperature&quot;,
    y = &quot;Daily PM 2.5 AQI&quot;,
    title = &quot;Daily PM 2.5 AQI VS. Daily Average Temperature Feb-Apr in 2020&quot;
  )</code></pre>
<p><img src="regression_analysis_files/figure-gfm/unnamed-chunk-13-1.png" width="90%" /></p>
<p>Fit a linear model.</p>
<pre class="r"><code>fit2 = lm(pm25 ~tavg, data = pm25_tavg_df)
summary(fit2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = pm25 ~ tavg, data = pm25_tavg_df)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -95.51 -31.45  -3.12  26.22 480.43 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 113.7598     2.6676  42.645   &lt;2e-16 ***
## tavg         -0.4239     0.1963  -2.159   0.0311 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 47.51 on 792 degrees of freedom
## Multiple R-squared:  0.005853,   Adjusted R-squared:  0.004598 
## F-statistic: 4.663 on 1 and 792 DF,  p-value: 0.03112</code></pre>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
