<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Project Report</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="initial_analysis.html">Data Exploration</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Data Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="test_fei.html">Hypothesis Test</a>
    </li>
    <li>
      <a href="regression_analysis.html">Regression Analysis</a>
    </li>
  </ul>
</li>
<li>
  <a href="Map_of_China.html">Map</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="project_proposal.html">About</a>
</li>
<li>
  <a href="mailto:&lt;ly2565@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/liny0907/p8105_final_project.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Project Report</h1>

</div>


<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>Recently, the COVID-19 pandemic has been a huge challenge for human beings. It was first identified in Wuhan, China in late December 2019, and then rapidly spread out worldwide. In order to contain the sudden COVID-19 outbreak, China implemented the lockdown policy in early February 2020, minimizing industrial, transportational, and commercial activities. Although the lockdown caused a tremendous economic loss, previous research had shown that the air condition in the top four megacities of China improved significantly during the lockdown period due to a dramatic decrease in automobile and industrial emissions (Wang et al., 2020). Bearing this in mind, we are motivated to find out whether “lockdown improves overall air quality” is a common phenomenon in Chinese cities including but not only limited to megacities. In addition, if there is indeed an association between lockdown and overall air quality, we are also interested in exploring the relationship between air quality improvement and other potentially correlated variables, for example, GDP, population, and temperature.</p>
</div>
<div id="related-work" class="section level2">
<h2>Related Work</h2>
<ol style="list-style-type: decimal">
<li>Positive effects of COVID-19 lockdown on air quality of industrial cities (Ankleshwar and Vapi) of Western India. [link] (<a href="https://www.nature.com/articles/s41598-021-83393-9" class="uri">https://www.nature.com/articles/s41598-021-83393-9</a>)</li>
<li>Impacts of primary emissions and secondary aerosol formation on air pollution in an urban area of China during the COVID-19 lockdown. [link] (<a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7997682/" class="uri">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7997682/</a>)</li>
<li>Four-Month Changes in Air Quality during and after the COVID-19 Lockdown in Six Megacities in China. [link] (<a href="https://pubs.acs.org/doi/10.1021/acs.estlett.0c00605" class="uri">https://pubs.acs.org/doi/10.1021/acs.estlett.0c00605</a>)</li>
</ol>
</div>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>The lockdown period started from early February to late April 2020. To ensure complete data coverage, we applied air quality data from February 1st to April 30th , 2020. Out of over 600 Chinese cities, we selected 30 representative ones based on geographical locations. For convenience, they are either municipalities or provincial capitals.</p>
<p>It has been established that seasonal variation does have a significant impact on air quality. Therefore, to control for the effects that different seasons have on air quality, we compared 30 cities’ air quality data during the lockdown period with the data during the same time period in 2019.</p>
<p>The air condition in a given area is usually denoted by the Air Quality Index (AQI), which is a variable describing the daily level of air pollution for five major pollutants. Each pollutant has its own AQI and for the purpose of this project, we will limit intended study objects to PM2.5, PM10, and NO2.</p>
</div>
<div id="questions" class="section level2">
<h2>Questions</h2>
<ol style="list-style-type: decimal">
<li><p>Is there a positive relationship between lockdown and air quality in the 30 cities that we are interested in? In other words, does lockdown improve the overall air quality level in each city?</p></li>
<li><p>Since the 30 cities are characterized by distinct locations, we are further interested in exploring whether location affects air quality improvement as well. If this statement holds, then which geographical area had the most significant improvement? Which one had the least?</p></li>
<li><p>The AQI is divided into 6 categories according to its value. Arranged in an ascending order, they are Good, Moderate, Unhealthy for Sensitive Groups, Unhealthy, Very Unhealthy, and Hazardous. Considering that the 30 cities are of different conditions, we want to investigate whether each city shares the same distribution of AQI categories or not.</p></li>
<li><p>Besides lockdown, are there any other potential variables that might be correlated with air quality improvement? We have come up with possible variables like GDP, population, and temperature and will conduct multiple linear regression to see if they are related.</p></li>
</ol>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<div id="data-source" class="section level3">
<h3>Data Source</h3>
</div>
<div id="data-processing-and-cleaning" class="section level3">
<h3>Data Processing and Cleaning</h3>
</div>
<div id="data-description" class="section level3">
<h3>Data Description</h3>
</div>
</div>
<div id="exploratory-analysis" class="section level2">
<h2>Exploratory Analysis</h2>
</div>
<div id="hypothesis-test-and-analysis" class="section level2">
<h2>Hypothesis Test and Analysis</h2>
<div id="chi-squared-test" class="section level3">
<h3>Chi-Squared Test</h3>
<pre class="r"><code>knitr::opts_chunk$set(echo = TRUE)

library(magrittr)
library(dplyr)
library(pivottabler)
library(tidyverse)
library(ggridges)
library(modelr)
library(mgcv)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = &quot;90%&quot;
)
theme_set(theme_minimal() + theme(legend.position = &quot;bottom&quot;))
options(
  ggplot2.continuous.colour = &quot;viridis&quot;,
  ggplot2.continuous.fill = &quot;viridis&quot;
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

city_30_df_pm25 = tibble(
  file = list.files(&quot;30_cities_data&quot;)) %&gt;% 
  mutate(
    city = str_remove(file, &quot;-air-quality.csv&quot;),
    path = str_c(&quot;30_cities_data/&quot;, file),
    data = map(path, read_csv)
  ) %&gt;% 
  unnest(data) %&gt;% 
  select(-file, -path) %&gt;% 
  mutate(
    city = str_to_title(city),
    date = as.Date(date, format = &quot;%Y/%m/%d&quot;)) %&gt;% 
  select(city,date,pm25)

pm25_2020 = 
  city_30_df_pm25 %&gt;% 
  filter(date &gt; &quot;2020-01-31&quot; &amp; date &lt; &quot;2020-05-01&quot;) %&gt;% 
  mutate(date = format(date, format = &quot;%y-%m-%d&quot;)) %&gt;% 
  select(city, date, pm25)


pm25_2019 = 
  city_30_df_pm25 %&gt;% 
  filter(date &gt; &quot;2019-01-31&quot; &amp; date &lt; &quot;2019-05-01&quot;) %&gt;% 
  mutate(date = format(date, format = &quot;%y-%m-%d&quot;)) %&gt;% 
  select(city, date, pm25)

pm25_2018 = 
  city_30_df_pm25 %&gt;% 
  filter(date &gt; &quot;2018-01-31&quot; &amp; date &lt; &quot;2018-05-01&quot;) %&gt;% 
  mutate(date = format(date, format = &quot;%y-%m-%d&quot;)) %&gt;% 
  select(city, date, pm25)

pm25_2017 = 
  city_30_df_pm25 %&gt;% 
  filter(date &gt; &quot;2017-01-31&quot; &amp; date &lt; &quot;2017-05-01&quot;) %&gt;% 
  mutate(date = format(date, format = &quot;%y-%m-%d&quot;)) %&gt;% 
  select(city, date, pm25)

pm25_171819 = rbind(pm25_2017,pm25_2018,pm25_2019)

pm25_1920 = rbind(pm25_2020,pm25_2019)</code></pre>
<p>Are cities and air quality level dependent at 5% level of significance? In other words, given the data collected above, is there a relationship between the cities and the level of air quality that they have obtained?</p>
<p>Null hypothesis (H0): the air quality level and the different cities variables of the contingency table are independent in 2020 between February to April.</p>
<p>Alternative hypothesis (H1): the air quality level and the different cities variables of the contingency table are dependent in 2020 between February to April.</p>
<pre class="r"><code>city_PM25 = pm25_2020 %&gt;%
  drop_na() %&gt;%
  select(city,pm25) %&gt;%
  mutate(level = as.character(pm25)) %&gt;%
  mutate(
    level = case_when(
      pm25 &lt;= 50 ~ &#39;Good&#39;,
      pm25 &lt;= 100 ~ &#39;Moderate&#39;,
      pm25 &lt;= 150 ~ &#39;Unhealthy for Sensitive People&#39;,
      pm25 &lt;= 200 ~ &#39; Unhealthy&#39;,
      pm25 &lt;= 300 ~ &#39;Very Unhealthy&#39;,
      pm25 &lt;= 500 ~ &#39;Hazardous&#39;)) %&gt;%
  arrange(city,level,pm25)

city_level =
  city_PM25 %&gt;%
  group_by(city,level) %&gt;%
  summarise(n = n()) %&gt;%
  pivot_wider(names_from = &quot;level&quot;, values_from = &quot;n&quot;)

city_level[is.na(city_level)] = 0 </code></pre>
<div id="air-quality-level-table" class="section level4">
<h4>Air Quality Level Table</h4>
<pre class="r"><code>airquality_level = read.csv(&quot;test (Fei)/city_air_quality_level.csv&quot;, row.names = 1 )
knitr::kable(airquality_level)</code></pre>
<table>
<colgroup>
<col width="13%" />
<col width="5%" />
<col width="9%" />
<col width="31%" />
<col width="10%" />
<col width="15%" />
<col width="10%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Good</th>
<th align="right">Moderate</th>
<th align="right">Unhealthy.for.Sensitive.People</th>
<th align="right">Unhealthy</th>
<th align="right">Very.Unhealthy</th>
<th align="right">Hazardous</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Beijing</td>
<td align="right">19</td>
<td align="right">31</td>
<td align="right">23</td>
<td align="right">14</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">90</td>
</tr>
<tr class="even">
<td align="left">Changchun</td>
<td align="right">2</td>
<td align="right">29</td>
<td align="right">37</td>
<td align="right">8</td>
<td align="right">7</td>
<td align="right">5</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Changsha</td>
<td align="right">2</td>
<td align="right">17</td>
<td align="right">54</td>
<td align="right">15</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Chengdu</td>
<td align="right">1</td>
<td align="right">22</td>
<td align="right">47</td>
<td align="right">18</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Chongqing</td>
<td align="right">0</td>
<td align="right">20</td>
<td align="right">53</td>
<td align="right">15</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Fuzhou</td>
<td align="right">9</td>
<td align="right">56</td>
<td align="right">23</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Guangzhou</td>
<td align="right">17</td>
<td align="right">52</td>
<td align="right">16</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Guiyang</td>
<td align="right">0</td>
<td align="right">42</td>
<td align="right">43</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Harbin</td>
<td align="right">7</td>
<td align="right">36</td>
<td align="right">25</td>
<td align="right">12</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">87</td>
</tr>
<tr class="even">
<td align="left">Hefei</td>
<td align="right">3</td>
<td align="right">45</td>
<td align="right">36</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Jinan</td>
<td align="right">1</td>
<td align="right">21</td>
<td align="right">47</td>
<td align="right">19</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Kunming</td>
<td align="right">1</td>
<td align="right">50</td>
<td align="right">36</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Lanzhou</td>
<td align="right">0</td>
<td align="right">26</td>
<td align="right">62</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Lhasa</td>
<td align="right">56</td>
<td align="right">32</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Nanchang</td>
<td align="right">0</td>
<td align="right">28</td>
<td align="right">50</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Nanjing</td>
<td align="right">0</td>
<td align="right">42</td>
<td align="right">39</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">85</td>
</tr>
<tr class="odd">
<td align="left">Nanning</td>
<td align="right">10</td>
<td align="right">52</td>
<td align="right">22</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Shanghai</td>
<td align="right">5</td>
<td align="right">49</td>
<td align="right">29</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Shenyang</td>
<td align="right">1</td>
<td align="right">28</td>
<td align="right">33</td>
<td align="right">24</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Shenzhen</td>
<td align="right">2</td>
<td align="right">67</td>
<td align="right">17</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Shijiazhuang</td>
<td align="right">0</td>
<td align="right">21</td>
<td align="right">37</td>
<td align="right">24</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Suzhou</td>
<td align="right">0</td>
<td align="right">33</td>
<td align="right">43</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Taiyuan</td>
<td align="right">2</td>
<td align="right">29</td>
<td align="right">32</td>
<td align="right">20</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Tianjin</td>
<td align="right">9</td>
<td align="right">29</td>
<td align="right">27</td>
<td align="right">21</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Wuhan</td>
<td align="right">1</td>
<td align="right">20</td>
<td align="right">55</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Wulumuqi</td>
<td align="right">3</td>
<td align="right">46</td>
<td align="right">22</td>
<td align="right">11</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Xian</td>
<td align="right">0</td>
<td align="right">19</td>
<td align="right">44</td>
<td align="right">19</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Xining</td>
<td align="right">0</td>
<td align="right">28</td>
<td align="right">58</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Yinchuan</td>
<td align="right">0</td>
<td align="right">57</td>
<td align="right">24</td>
<td align="right">7</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">Zhengzhou</td>
<td align="right">2</td>
<td align="right">18</td>
<td align="right">47</td>
<td align="right">19</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">88</td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="right">153</td>
<td align="right">1045</td>
<td align="right">1081</td>
<td align="right">306</td>
<td align="right">44</td>
<td align="right">9</td>
<td align="right">2638</td>
</tr>
</tbody>
</table>
<pre class="r"><code>chisq.test(airquality_level, simulate.p.value = TRUE)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with simulated p-value (based on 2000
##  replicates)
## 
## data:  airquality_level
## X-squared = 1363.2, df = NA, p-value = 0.0004998</code></pre>
<pre class="r"><code>qchisq(0.05, 174, lower.tail = TRUE) </code></pre>
<pre><code>## [1] 144.494</code></pre>
</div>
<div id="chi-squared-test-result" class="section level4">
<h4>Chi-Squared Test Result</h4>
<p>For a Chi-square test, the p-value(0.0004998) that is less than 0.05 significance level. We can reject the null hypothesis (H0) and indicates there is no evidence to conclude that the air quality level and the different cities variables of the contingency table are independent and there is a relationship between them.</p>
</div>
</div>
<div id="two-sample-paired-t-test" class="section level3">
<h3>Two-Sample Paired T-test</h3>
<p>Null hypothesis (H0): The true mean difference between the average number of AQI (pm25) for each 30 cities from February to April 2020 and the average number between 2017-2019 is equal to zero.</p>
<p>Alternative hypothesis (H1): The true mean difference between the average number of AQI (pm25) for each 30 cities from February to April 2020 and the average number between 2017-2019 is not equal to zero.</p>
<pre class="r"><code>mean_20 = pm25_2020 %&gt;%
  drop_na() %&gt;% 
  select(-date) %&gt;%
  group_by(city) %&gt;%
  summarise(mean = mean(pm25)) %&gt;%
  select(mean) %&gt;%
  pull()


mean_171819 = pm25_171819 %&gt;%
  drop_na() %&gt;% 
  select(-date) %&gt;%
  group_by(city) %&gt;%
  summarise(mean = mean(pm25)) %&gt;%
  select(mean) %&gt;%
  pull()

table1 = pm25_2020 %&gt;%
  drop_na() %&gt;% 
  select(-date) %&gt;%
  group_by(city) %&gt;%
  summarise(mean_2020 = mean(pm25))

table2 = pm25_171819 %&gt;%
  drop_na() %&gt;% 
  select(-date) %&gt;%
  group_by(city) %&gt;%
  summarise(mean_2017_2018_2019 = mean(pm25)) %&gt;%
  select(-city) 

table3 = pm25_2020 %&gt;%
  drop_na() %&gt;% 
  select(-date) %&gt;%
  group_by(city) %&gt;%
  summarise(standard_deviation_2020 = sd(pm25))

table4 = pm25_171819 %&gt;%
  drop_na() %&gt;% 
  select(-date) %&gt;%
  group_by(city) %&gt;%
  summarise(standard_deviation_2017_2018_2019 = sd(pm25)) %&gt;%
  select(-city) </code></pre>
<div id="t-test-table" class="section level4">
<h4>T Test Table</h4>
<div id="mean-table" class="section level5">
<h5>Mean Table</h5>
<pre class="r"><code>knitr::kable(bind_cols(table1,table2))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">city</th>
<th align="right">mean_2020</th>
<th align="right">mean_2017_2018_2019</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Beijing</td>
<td align="right">101.08889</td>
<td align="right">122.56180</td>
</tr>
<tr class="even">
<td align="left">Changchun</td>
<td align="right">129.68182</td>
<td align="right">130.83146</td>
</tr>
<tr class="odd">
<td align="left">Changsha</td>
<td align="right">119.76136</td>
<td align="right">131.89139</td>
</tr>
<tr class="even">
<td align="left">Chengdu</td>
<td align="right">120.07955</td>
<td align="right">138.58052</td>
</tr>
<tr class="odd">
<td align="left">Chongqing</td>
<td align="right">118.37500</td>
<td align="right">122.62547</td>
</tr>
<tr class="even">
<td align="left">Fuzhou</td>
<td align="right">85.51136</td>
<td align="right">101.99625</td>
</tr>
<tr class="odd">
<td align="left">Guangzhou</td>
<td align="right">79.71591</td>
<td align="right">104.67416</td>
</tr>
<tr class="even">
<td align="left">Guiyang</td>
<td align="right">104.68182</td>
<td align="right">119.70037</td>
</tr>
<tr class="odd">
<td align="left">Harbin</td>
<td align="right">118.10227</td>
<td align="right">128.25468</td>
</tr>
<tr class="even">
<td align="left">Hefei</td>
<td align="right">99.15909</td>
<td align="right">133.51311</td>
</tr>
<tr class="odd">
<td align="left">Jinan</td>
<td align="right">121.12500</td>
<td align="right">153.87640</td>
</tr>
<tr class="even">
<td align="left">Kunming</td>
<td align="right">93.87500</td>
<td align="right">107.58801</td>
</tr>
<tr class="odd">
<td align="left">Lanzhou</td>
<td align="right">109.44318</td>
<td align="right">127.83895</td>
</tr>
<tr class="even">
<td align="left">Lhasa</td>
<td align="right">47.64773</td>
<td align="right">70.38202</td>
</tr>
<tr class="odd">
<td align="left">Nanchang</td>
<td align="right">117.04545</td>
<td align="right">122.91011</td>
</tr>
<tr class="even">
<td align="left">Nanjing</td>
<td align="right">103.63529</td>
<td align="right">131.98876</td>
</tr>
<tr class="odd">
<td align="left">Nanning</td>
<td align="right">89.17045</td>
<td align="right">102.31461</td>
</tr>
<tr class="even">
<td align="left">Shanghai</td>
<td align="right">96.43182</td>
<td align="right">121.94382</td>
</tr>
<tr class="odd">
<td align="left">Shenyang</td>
<td align="right">124.36364</td>
<td align="right">131.01124</td>
</tr>
<tr class="even">
<td align="left">Shenzhen</td>
<td align="right">86.70455</td>
<td align="right">108.02622</td>
</tr>
<tr class="odd">
<td align="left">Shijiazhuang</td>
<td align="right">132.56818</td>
<td align="right">170.88015</td>
</tr>
<tr class="even">
<td align="left">Suzhou</td>
<td align="right">112.28409</td>
<td align="right">138.64419</td>
</tr>
<tr class="odd">
<td align="left">Taiyuan</td>
<td align="right">123.22727</td>
<td align="right">141.02622</td>
</tr>
<tr class="even">
<td align="left">Tianjin</td>
<td align="right">112.10227</td>
<td align="right">131.56015</td>
</tr>
<tr class="odd">
<td align="left">Wuhan</td>
<td align="right">119.30682</td>
<td align="right">148.14286</td>
</tr>
<tr class="even">
<td align="left">Wulumuqi</td>
<td align="right">111.55682</td>
<td align="right">153.50562</td>
</tr>
<tr class="odd">
<td align="left">Xian</td>
<td align="right">130.88636</td>
<td align="right">156.21348</td>
</tr>
<tr class="even">
<td align="left">Xining</td>
<td align="right">112.95455</td>
<td align="right">125.71536</td>
</tr>
<tr class="odd">
<td align="left">Yinchuan</td>
<td align="right">95.00000</td>
<td align="right">113.98876</td>
</tr>
<tr class="even">
<td align="left">Zhengzhou</td>
<td align="right">125.65909</td>
<td align="right">153.83895</td>
</tr>
</tbody>
</table>
</div>
<div id="standard-deviation-table" class="section level5">
<h5>Standard Deviation Table</h5>
<pre class="r"><code>knitr::kable(bind_cols(table3,table4))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">city</th>
<th align="right">standard_deviation_2020</th>
<th align="right">standard_deviation_2017_2018_2019</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Beijing</td>
<td align="right">53.622410</td>
<td align="right">58.27449</td>
</tr>
<tr class="even">
<td align="left">Changchun</td>
<td align="right">71.154930</td>
<td align="right">41.89880</td>
</tr>
<tr class="odd">
<td align="left">Changsha</td>
<td align="right">31.946433</td>
<td align="right">35.77939</td>
</tr>
<tr class="even">
<td align="left">Chengdu</td>
<td align="right">31.925280</td>
<td align="right">31.39782</td>
</tr>
<tr class="odd">
<td align="left">Chongqing</td>
<td align="right">27.455842</td>
<td align="right">32.98602</td>
</tr>
<tr class="even">
<td align="left">Fuzhou</td>
<td align="right">26.220547</td>
<td align="right">31.28411</td>
</tr>
<tr class="odd">
<td align="left">Guangzhou</td>
<td align="right">30.560266</td>
<td align="right">32.54474</td>
</tr>
<tr class="even">
<td align="left">Guiyang</td>
<td align="right">25.447510</td>
<td align="right">27.04869</td>
</tr>
<tr class="odd">
<td align="left">Harbin</td>
<td align="right">82.209578</td>
<td align="right">51.92377</td>
</tr>
<tr class="even">
<td align="left">Hefei</td>
<td align="right">26.941779</td>
<td align="right">29.62705</td>
</tr>
<tr class="odd">
<td align="left">Jinan</td>
<td align="right">33.247872</td>
<td align="right">35.76158</td>
</tr>
<tr class="even">
<td align="left">Kunming</td>
<td align="right">25.200717</td>
<td align="right">27.87814</td>
</tr>
<tr class="odd">
<td align="left">Lanzhou</td>
<td align="right">17.747823</td>
<td align="right">25.46043</td>
</tr>
<tr class="even">
<td align="left">Lhasa</td>
<td align="right">9.629982</td>
<td align="right">20.77276</td>
</tr>
<tr class="odd">
<td align="left">Nanchang</td>
<td align="right">27.839404</td>
<td align="right">33.82973</td>
</tr>
<tr class="even">
<td align="left">Nanjing</td>
<td align="right">25.560780</td>
<td align="right">29.50181</td>
</tr>
<tr class="odd">
<td align="left">Nanning</td>
<td align="right">33.432802</td>
<td align="right">30.92044</td>
</tr>
<tr class="even">
<td align="left">Shanghai</td>
<td align="right">43.508170</td>
<td align="right">38.68478</td>
</tr>
<tr class="odd">
<td align="left">Shenyang</td>
<td align="right">43.895430</td>
<td align="right">41.74101</td>
</tr>
<tr class="even">
<td align="left">Shenzhen</td>
<td align="right">22.903676</td>
<td align="right">26.22566</td>
</tr>
<tr class="odd">
<td align="left">Shijiazhuang</td>
<td align="right">45.105444</td>
<td align="right">66.73903</td>
</tr>
<tr class="even">
<td align="left">Suzhou</td>
<td align="right">29.967396</td>
<td align="right">33.18705</td>
</tr>
<tr class="odd">
<td align="left">Taiyuan</td>
<td align="right">45.217159</td>
<td align="right">45.75691</td>
</tr>
<tr class="even">
<td align="left">Tianjin</td>
<td align="right">45.379888</td>
<td align="right">55.96237</td>
</tr>
<tr class="odd">
<td align="left">Wuhan</td>
<td align="right">28.383806</td>
<td align="right">30.04290</td>
</tr>
<tr class="even">
<td align="left">Wulumuqi</td>
<td align="right">55.372689</td>
<td align="right">76.66299</td>
</tr>
<tr class="odd">
<td align="left">Xian</td>
<td align="right">37.331516</td>
<td align="right">49.79993</td>
</tr>
<tr class="even">
<td align="left">Xining</td>
<td align="right">19.740215</td>
<td align="right">29.23179</td>
</tr>
<tr class="odd">
<td align="left">Yinchuan</td>
<td align="right">30.217982</td>
<td align="right">33.16596</td>
</tr>
<tr class="even">
<td align="left">Zhengzhou</td>
<td align="right">34.516325</td>
<td align="right">46.23868</td>
</tr>
</tbody>
</table>
<pre class="r"><code>t.test(mean_20, mean_171819, paired = T)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  mean_20 and mean_171819
## t = -11.116, df = 29, p-value = 5.679e-12
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -23.87243 -16.45294
## sample estimates:
## mean of the differences 
##               -20.16268</code></pre>
<pre class="r"><code>qt(0.05, 29)</code></pre>
<pre><code>## [1] -1.699127</code></pre>
</div>
</div>
<div id="t-test-result" class="section level4">
<h4>T Test Result</h4>
<p>For a Two-Sample Paired T-test, the p-value(5.679e-12) that is less than 0.05 significance level. We can reject the null hypothesis (H0) and indicates there is no evidence to conclude that the true mean difference between the average number of AQI (pm25) for each 30 cities from February to April 2020 and the average number between 2017-2019 is equal to zero and there are different mean for each 30 cities between 2020 and 2017-2019.</p>
</div>
</div>
</div>
<div id="regression-analysis" class="section level2">
<h2>Regression Analysis</h2>
<div id="aqi-difference-vs-gdp-and-population" class="section level3">
<h3>AQI Difference vs GDP and Population</h3>
<div id="data-frame-for-regression-analysis" class="section level4">
<h4>Data frame for regression analysis</h4>
<pre class="r"><code>library(tidyverse)
library(ggridges)
library(modelr)
library(mgcv)
library(patchwork)

theme_set(theme_minimal() + theme(legend.position = &quot;bottom&quot;))

options(
  ggplot2.continuous.colour = &quot;viridis&quot;,
  ggplot2.continuous.fill = &quot;viridis&quot;
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

city_100_df = 
  tibble(
  file = list.files(&quot;100_cities_data&quot;)) %&gt;% 
  mutate(
    city = str_remove(file, &quot;-air-quality.csv&quot;),
    path = str_c(&quot;100_cities_data/&quot;, file),
    data = map(path, read_csv)
  ) %&gt;% 
  unnest(data) %&gt;% 
  select(-file, -path) %&gt;% 
  mutate(
    city = str_to_title(city),
    date = as.Date(date, format = &quot;%Y/%m/%d&quot;))

pm25_2020 = 
  city_100_df %&gt;% 
  filter(date &gt; &quot;2020-01-31&quot; &amp; date &lt; &quot;2020-05-01&quot;) %&gt;% 
  group_by(city) %&gt;%
  summarize(mean_pm25_2020 = mean(pm25, na.rm = T))
  
pm25_2019 = 
  city_100_df %&gt;% 
  filter(date &gt; &quot;2019-01-31&quot; &amp; date &lt; &quot;2019-05-01&quot;) %&gt;% 
  group_by(city) %&gt;%
  summarize(mean_pm25_2019 = mean(pm25, na.rm = T))

pm25_diff = 
  left_join(pm25_2020, pm25_2019) %&gt;% 
  mutate(pm25_diff = mean_pm25_2019 - mean_pm25_2020)

gdp_pop_df = 
  read_csv(&quot;data/gpd_and_popluation.csv&quot;) %&gt;% 
  janitor::clean_names() %&gt;% 
  mutate(
    gdp_trillion = gdp_billion / 1000,
    pop_million = population_thousand / 1000) %&gt;% 
  select(city, gdp_trillion, pop_million)

diff_gdp_pop_df = 
  left_join(pm25_diff, gdp_pop_df) %&gt;% 
  select(-mean_pm25_2020, -mean_pm25_2019)</code></pre>
<p>We learn that air quality improvement in a city may correlate to the city’s GDP and population, so we create a data frame containing mean pm2.5 AQI differences between 2019 and 2020, GDP and population in 2019 for 100 representative cities.</p>
<p>The resulting data frame of <code>diff_gdp_pop_df</code> contains 100 observations of 4 variables. Each row represents one unique city. Below are key variables:<br />
<code>city</code>: city name<br />
<code>pm25_diff</code>: difference of mean pm2.5 AQI during the lockdown period (Feb-Apr) between 2019 and 2020<br />
<code>gdp_trillion</code>: 2019 GDP in trillion<br />
<code>pop_million</code>: 2019 population in thousand<br />
</p>
</div>
<div id="find-appropriate-transformation" class="section level4">
<h4>Find Appropriate Transformation</h4>
<p>Since the boxcox function only works with positive values for the response variable y, we removed pm25_diff less than 0 to check if a transformation is appropriate here.</p>
<pre class="r"><code>pos_diff_gdp_pop_df =
  diff_gdp_pop_df %&gt;% 
  filter(pm25_diff &gt; 0)
  
fit = lm(pm25_diff ~gdp_trillion + pop_million, data = pos_diff_gdp_pop_df)
MASS::boxcox(fit)</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-9-1.png" width="90%" /></p>
<p>The box-cox plot shows that log-likelihood has the maximum value around lambda = 0.5, so square root of pm25_diff is the recommended transformation.</p>
</div>
<div id="mlr" class="section level4">
<h4>MLR</h4>
<pre class="r"><code>trans_diff_gdp_pop_df =
  pos_diff_gdp_pop_df %&gt;% 
  mutate(sqrt_pm25_diff = sqrt(pm25_diff))

trans_fit = lm(sqrt_pm25_diff ~gdp_trillion + pop_million, data = trans_diff_gdp_pop_df)

trans_fit %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable(caption = &quot;Linear Regression Results&quot;)</code></pre>
<table>
<caption>Linear Regression Results</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">3.7187826</td>
<td align="right">0.2799728</td>
<td align="right">13.2826555</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">gdp_trillion</td>
<td align="right">0.0436444</td>
<td align="right">0.3796025</td>
<td align="right">0.1149740</td>
<td align="right">0.9087190</td>
</tr>
<tr class="odd">
<td align="left">pop_million</td>
<td align="right">-0.0102924</td>
<td align="right">0.0529619</td>
<td align="right">-0.1943355</td>
<td align="right">0.8463464</td>
</tr>
</tbody>
</table>
<p>After fitting a linear model for sqrt(mean pm2.5 AQI difference) dependent on gdp_trillion and pop_million, gdp_trillion variable has a slope of 0.0436 and pop_million variable has a slope of -0.0103 with p values of 0.909 and 0.846 which are extremely large. Therefore, GDP and population in a city don’t have significant effects on predictions of air quality improvement, in other words, we don’t have enough evidence to support that air quality improvement has a linear relationship with GDP and population.</p>
</div>
<div id="model-diagnostics" class="section level4">
<h4>Model Diagnostics</h4>
<pre class="r"><code>par(mfrow = c(2,2))
plot(trans_fit)</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-11-1.png" width="90%" /> In residuals vs fitted plot, residuals appear to be evenly distributed around 0, indicating that residuals have constant variance. In normal QQ plot, a straight line is not seen, so our model violates the assumption that residuals are normally distributed. The scale-location plot shows that except for #11, residuals equally spread around a roughly horizontal line, confirming that residuals have constant variance. Finally, all the four plot show that there is an influential outlier labelled #11.</p>
</div>
<div id="cross-validation" class="section level4">
<h4>Cross Validation</h4>
<p>Fit three models for <code>sqrt_pm25_diff</code> vs. <code>gdp_trillion</code> and <code>pop_million</code>.</p>
<pre class="r"><code>nointer_linear_mod = lm(sqrt_pm25_diff ~ gdp_trillion + pop_million, data = trans_diff_gdp_pop_df)
inter_linear_mod = lm(sqrt_pm25_diff ~ gdp_trillion * pop_million, data = trans_diff_gdp_pop_df)
smooth_mod = gam(sqrt_pm25_diff ~ s(gdp_trillion, pop_million), data = trans_diff_gdp_pop_df)

trans_diff_gdp_pop_df %&gt;% 
  gather_predictions(nointer_linear_mod, inter_linear_mod, smooth_mod) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = gdp_trillion + pop_million, y = sqrt_pm25_diff)) + 
  geom_point(alpha = .5) +
  geom_line(aes(y = pred), color = &quot;red&quot;) + 
  facet_grid(~model) +
  labs(
    x = &quot;GDP in Billion + Population in Million&quot;,
    y = &quot;Sqrt(Mean PM2.5 AQI Difference)&quot;,
    title = &quot;Sqrt(Mean PM2.5 AQI Difference) vs GDP and Population&quot;)</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-12-1.png" width="90%" /></p>
<p>Cross validation for <code>sqrt_pm25_diff</code> vs. <code>gdp_trillion</code> and <code>pop_million</code>.</p>
<pre class="r"><code>cv_df = 
  crossv_mc(trans_diff_gdp_pop_df, 100) %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) %&gt;% 
  mutate(
    nointer_linear_mod  = map(train, ~lm(sqrt_pm25_diff ~ gdp_trillion + pop_million, data = .x)),
    inter_linear_mod = map(train, ~lm(sqrt_pm25_diff ~ gdp_trillion * pop_million, data = .x)),
    smooth_mod  = map(train, ~gam(sqrt_pm25_diff ~ s(gdp_trillion, pop_million), data = .x))) %&gt;% 
  mutate(
    rmse_nointer_linear = map2_dbl(nointer_linear_mod, test, ~rmse(model = .x, data = .y)),
    rmse_inter_linear = map2_dbl(inter_linear_mod, test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(smooth_mod, test, ~rmse(model = .x, data = .y))) 


cv_df %&gt;%
  select(starts_with(&quot;rmse&quot;)) %&gt;%
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_boxplot() +
  labs(
    x = &quot;Model&quot;,
    y = &quot;RMSE&quot;,
    title = &quot;Distribution of RMSE across Models (Log(Mean PM2.5 AQI Difference) vs GDP +Population)&quot;) +
  theme(
    title = element_text(size = 8, face = &quot;bold&quot;),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10))</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-13-1.png" width="90%" /></p>
<p>We then did cross validation for three different models of mean PM2.5 AQI difference vs. gdp_trillion and pop_million. The distribution of RMSE values for each model suggests that the smooth model works slightly better than two linear models. There is some improvement in predictive accuracy gained by allowing non-linearity, but it is not sufficient to justify this model.</p>
</div>
</div>
<div id="daily-aqi-vs-daily-average-temperature" class="section level3">
<h3>Daily AQI vs Daily Average Temperature</h3>
<div id="data-frame-for-regression-analysis-1" class="section level4">
<h4>Data frame for regression analysis</h4>
<pre class="r"><code>weather_df = 
  rnoaa::meteo_pull_monitors(
    c(&quot;CHM00054511&quot;, &quot;CHM00058362&quot;, &quot;CHM00050953&quot;, &quot;CHM00054342&quot;, &quot;CHM00055591&quot;, &quot;CHM00056294&quot;, &quot;CHM00056778&quot;, &quot;CHM00059287&quot;, &quot;CHM00057036&quot;, &quot;CHM00057494&quot;),
    var = c(&quot;PRCP&quot;, &quot;TAVG&quot;), 
    date_min = &quot;2020-02-01&quot;,
    date_max = &quot;2020-04-30&quot;) %&gt;%
  mutate(
    name = recode(
      id, 
      CHM00054511 = &quot;Beijing&quot;, 
      CHM00058362 = &quot;Shanghai&quot;,
      CHM00050953 = &quot;Harbin&quot;,
      CHM00054342 = &quot;Shenyang&quot;,
      CHM00055591 = &quot;Lhasa&quot;,
      CHM00056294 = &quot;Chengdu&quot;,
      CHM00056778 = &quot;Kunming&quot;,
      CHM00059287 = &quot;Guangzhou&quot;,
      CHM00057036 = &quot;Xian&quot;,
      CHM00057494 = &quot;Wuhan&quot;),
    tavg = tavg / 10,
    prcp = prcp / 10) %&gt;%
  select(-id) %&gt;% 
  rename(city = name) %&gt;% 
  relocate(city)

city_10_df =
  city_100_df %&gt;% 
  filter(date &gt; &quot;2020-01-31&quot; &amp; date &lt; &quot;2020-05-01&quot;) %&gt;% 
  filter(city %in% c(&quot;Beijing&quot;, &quot;Shanghai&quot;, &quot;Harbin&quot;, &quot;Shenyang&quot;, &quot;Lhasa&quot;, &quot;Chengdu&quot;, &quot;Kunming&quot;, &quot;Guangzhou&quot;, &quot;Xian&quot;, &quot;Wuhan&quot;))

pm25_tavg_df = 
  left_join(city_10_df, weather_df, by = c(&quot;city&quot;, &quot;date&quot;)) %&gt;% 
  arrange(date) %&gt;% 
  select(city, date, pm25, tavg) %&gt;% 
  filter(pm25 != &quot;NA&quot;)</code></pre>
<p>We also hypothesize that daily PM2.5 AQI may correlate to daily average temperature. We collect 02/2020 - 04/2020 temperature data for 10 representative cities in all the regions(East, South, West, North) to avoid bias caused by locations if possible. The resulting data frame has 882 observations of 4 variables. Below are the variables:<br />
<code>city</code>: city name<br />
<code>date</code>: the date on which PM2.5 AQI and average temperature were collected<br />
<code>pm25</code>: PM2.5 AQI on that day<br />
<code>tavg</code>: average temperature on that day</p>
</div>
<div id="find-appropriate-transformation-1" class="section level4">
<h4>Find appropriate transformation</h4>
<pre class="r"><code>fit_tavg = lm(pm25 ~tavg, data = pm25_tavg_df)
MASS::boxcox(fit_tavg)</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-15-1.png" width="90%" /></p>
<p>The box-cox plot shows that log-likelihood has the maximum value around lambda = 0, so natural logarithm of pm25_diff is the recommended transformation.</p>
</div>
<div id="mlr-1" class="section level4">
<h4>MLR</h4>
<pre class="r"><code>log_pm25_tavg_df =
  pm25_tavg_df %&gt;% 
  mutate(lnpm25 = log(pm25))

log_fit = lm(lnpm25 ~tavg, data = log_pm25_tavg_df)
log_fit %&gt;%
  broom::tidy() %&gt;% 
  knitr::kable(caption = &quot;Linear Regression Results&quot;)</code></pre>
<table>
<caption>Linear Regression Results</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">4.5007147</td>
<td align="right">0.0250049</td>
<td align="right">179.993116</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">tavg</td>
<td align="right">0.0028357</td>
<td align="right">0.0019151</td>
<td align="right">1.480744</td>
<td align="right">0.1390328</td>
</tr>
</tbody>
</table>
<p>Based on this table, tavg variable has a slope of 0.0028 with p value of 0.139 which is larger than 0.05. Therefore, daily average temperature in a city may not have significant effects on predictions of air quality improvement. However, the p value of this model is much less than that of the model mean PM2.5 AQI difference vs GDP and population, meaning the linear model daily PM2.5 AQI vs daily average temperature is more significant.</p>
</div>
<div id="model-diagnostics-1" class="section level4">
<h4>Model diagnostics</h4>
<pre class="r"><code>par(mfrow = c(2,2))
plot(log_fit)</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-17-1.png" width="90%" /></p>
<p>Residuals seem to be evenly distributed around 0, which is an indication of constant variance. There are some potential outliers, such as #766 and 163. The normal QQ plot shows a roughly straight line, meaning residuals are normally distributed. Therefore, our model fitting for daily pm2.5 AQI difference dependent on daily average temperature doesn’t violate assumptions on residuals.</p>
</div>
<div id="cross-validation-1" class="section level4">
<h4>Cross validation</h4>
<p>Fit three models for <code>lnpm25</code> vs. <code>tavg</code>.</p>
<pre class="r"><code>linear_mod_tavg = lm(lnpm25 ~ tavg, data = log_pm25_tavg_df)
smooth_mod_tavg = gam(lnpm25 ~ s(tavg), data = log_pm25_tavg_df)
wiggly_mod_tavg = gam(lnpm25 ~ s(tavg, k = 30), sp = 10e-6, data = log_pm25_tavg_df)

log_pm25_tavg_df %&gt;% 
  gather_predictions(linear_mod_tavg, smooth_mod_tavg, wiggly_mod_tavg) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = tavg, y = lnpm25)) + 
  geom_point(alpha = .5) +
  geom_line(aes(y = pred), color = &quot;red&quot;) + 
  facet_grid(~model) +
  labs(
    x = &quot;Daily Average Temperature&quot;,
    y = &quot;Log(Daily PM2.5 AQI)&quot;,
    title = &quot;Models of Log(Daily PM2.5 AQI) vs Daily Average Temperature&quot;
  )</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-18-1.png" width="90%" /></p>
<p>Cross validation for <code>lnpm25</code> vs. <code>tavg</code>.</p>
<pre class="r"><code>cv_tavg_df = 
  crossv_mc(log_pm25_tavg_df, 100) %&gt;% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) %&gt;% 
  mutate(
    linear_mod  = map(train, ~lm(lnpm25 ~ tavg, data = .x)),
    smooth_mod  = map(train, ~mgcv::gam(lnpm25 ~ s(tavg), data = .x)),
    wiggly_mod  = map(train, ~gam(lnpm25 ~ s(tavg, k = 30), sp = 10e-6, data = .x))) %&gt;% 
  mutate(
    rmse_linear = map2_dbl(linear_mod, test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(smooth_mod, test, ~rmse(model = .x, data = .y)),
    rmse_wiggly = map2_dbl(wiggly_mod, test, ~rmse(model = .x, data = .y)))

cv_tavg_df %&gt;% 
  select(starts_with(&quot;rmse&quot;)) %&gt;% 
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_boxplot() +
  labs(
    x = &quot;Model&quot;,
    y = &quot;RMSE&quot;,
    title = &quot;Distribution of RMSE across Models (Log(pm2.5 AQI) vs Tavg)&quot;)</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-19-1.png" width="90%" /> The distribution of RMSE values for each model fitting daily PM2.5 AQI vs daily average temperature suggests that the smooth model works better than linear and wiggly models.</p>
</div>
</div>
<div id="regression-conclusions" class="section level3">
<h3>Regression Conclusions</h3>
<p>We don’t have enough evidence to support that during the lockdown period, air quality improvement in a city has a significant linear relationship with GDP and population. The daily PM2.5 AQI isn’t significantly correlated to daily average temperature either. The two non-significant linear models may be due to small sample size, so a larger sample size may be helpful for getting significant models.</p>
</div>
</div>
<div id="discussion-and-conclusion" class="section level2">
<h2>Discussion and Conclusion</h2>
<p>Overall, we found that there was a significant relationship between the lockdown and air quality level for 30 cities combined, which was consistent with our initial hypothesis. The air quality for the 30 cities was generally better during the lockdown compared to the same period in the past year. However, contrary to what we expected before, none of GDP, population, and temperature served as predictors for air quality improvement after we conducted the regression analysis.</p>
<p>The map of China included in our analysis exhibits the distribution of magnitude of air quality improvement during the lockdown period across 100 cities. Each dot represents a city we selected, and the color indicates its degree of air quality improvement. The bluer the dot is, the more improvement it had made.</p>
<p>We can see that most cities with significant air quality improvement tend to cluster in the North China and Yangtze River Delta region. This might be partially explained by the economic structure. Industrial output value accounts for a relatively large proportion of GDP in these two areas. Normally, there are a lot of industrial activities going on there. However, during the lockdown period, nearly all of them were partially or completely suspended. As industry does have an unignorable negative impact on air quality, it’s not difficult to see why notable air quality improvement could be observed in these two regions.</p>
<p>There are a few notable limitations in our project. Firstly, besides GDP, population, and temperature, there might be variables that are more closely related to air quality improvements, for example, industrial output value. However, due to limited access to expected datasets, we failed to include it in our regression model. In addition, the 30 cities we selected are not representative since they are all relatively large in terms of scale. There are many more small cities that we hadn’t investigated. Therefore, the results we obtained in this project were not generalizable to all Chinese cities. Finally, the datasets we found contained a lot of missing values, which might undermine the reliability and validity of our study in some degree.</p>
<p>This project also further implicates that current economic and social development is nearly always at the expense of environmental degradation. However, there are promising ways that could tackle this problem effectively. For example, choosing means of transportation that are more environmental-friendly, using cleaner and renewable energies for production, and reducing hazardous substance emission could all ameliorate the situation to some extent.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
